server:
    port: 0

spring:
  jpa:
    hibernate:
      ddl-auto: update

app:
    clusterId: ${CLUSTER_ID}
    appDomain: ${APP_DOMAIN:localhost}
    kafka:
        urls: ${KAFKA_URLS:localhost:9092}
        timeout: 15000
        groupId: ${KAFKA_GROUP_ID:market-realtime}
        topic:
          marketData: ${KAFKA_TOPIC_MARKET_DATA:market-data}

    mqtt:
        url: ${MQTT_URL:tcp://localhost:1883}
        username: ${MQTT_USERNAME:}
        password: ${MQTT_PASSWORD:}
        topic:
          marketData: ${MQTT_TOPIC_MARKET_DATA:market-data}

    database:
      url: ${DB_HOST:localhost}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}

    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}
      database: ${REDIS_DATABASE}

    mail:
      host: ${MAIL_HOST:smtp.example.com}
      port: ${MAIL_PORT:587}
      username: ${MAIL_USERNAME:}
      password: ${MAIL_PASSWORD:}

    uri:
      user:
        create: "/user/create"
        update: "/user/update"
        delete: "/user/delete"
        updatePassword: "/user/updatePassword"
      stock:
        create: "/stock/create"
        update: "/stock/update"
        delete: "/stock/delete"
        updateIndustryRatios: "/stock/updateIndustryRatios"
        updateMatchPrice: "/stock/updateMatchPrice/"
      subscription:
        create: "/subscription/create"
        update: "/subscription/update"
        delete: "/subscription/delete"
      ahpConfig:
        create: "/ahpConfig/create"
        update: "/ahpConfig/update"
      stockYearData:
        create: "/stockYearData/create"
        update: "/stockYearData/update/"
        delete: "/stockYearData/delete"


