server:
  port: 0

app:
  clusterId: ${CLUSTER_ID}
  kafka:
    urls: ${KAFKA_URLS:localhost:9092}
    timeout: 15000
    topic:
      marketData: ${KAFKA_TOPIC_MARKET_DATA:market-data}

  mqtt:
    url: ${MQTT_URL:tcp://localhost:1883}
    username: ${MQTT_USERNAME:}
    password: ${MQTT_PASSWORD:}
    topic:
      marketData: ${MQTT_TOPIC_MARKET_DATA:market-data}

  dataFeed:
    url: ${DATAFEED_URL:wss://datafeed-lts-krx.dnse.com.vn:443/wss}
    username: ${DATAFEED_USERNAME:}
    password: ${DATAFEED_PASSWORD:}
    timeout: 15000
